name: release

on:
  push:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Build'

env:
  CACHE_VERSION: 5
  DEBIAN_FRONTEND: noninteractive
  PAWPAW_SKIP_LTO: 1

jobs:
  # linux with win64 cross-compilation
  win64:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Set up cache
      uses: actions/cache@v3
      id: cache
      with:
        path: |
          ~/PawPawBuilds
        key: win64-v${{ env.CACHE_VERSION }}
    - name: Restore debian packages cache
      run: |
        if [ -d ~/PawPawBuilds/debs ] && [ "$(ls ~/PawPawBuilds/debs | wc -l)" -ne 0 ]; then \
          sudo cp ~/PawPawBuilds/debs/*.deb /var/cache/apt/archives/; \
        fi
    - name: Fix GitHub's mess
      run: |
        sudo rm -f /etc/apt/sources.list.d/microsoft-prod.list
        sudo apt-get update -qq
        sudo apt-get install -yqq --allow-downgrades libgd3/jammy
        sudo apt-get purge -yqq libmono* moby* mono* msbuild* php* libgdiplus libpcre2-posix3 nuget
    - name: Set up dependencies
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update -qq
        sudo apt-get install -y autopoint build-essential curl cmake jq llvm meson mingw-w64 qttools5-dev qttools5-dev-tools xvfb \
          binutils-mingw-w64-x86-64 g++-mingw-w64-x86-64 mingw-w64 wine-stable wine32
    - name: Cache debian packages
      run: |
        mkdir -p ~/PawPawBuilds/debs
        sudo mv /var/cache/apt/archives/*.deb ~/PawPawBuilds/debs/
    - name: Bootstrap win64 cross-compiled
      shell: bash
      run: |
        ./PawPaw/bootstrap-jack2.sh win64 && ./PawPaw/bootstrap-qt.sh win64 && ./PawPaw/.cleanup.sh win64
    - name: Build win64 cross-compiled
      shell: bash
      if: steps.cache.outputs.cache-hit == 'true'
      run: |
        xvfb-run ./pack-jack2-version.sh win64
    - name: Set sha8
      id: slug
      run: echo "::set-output name=sha8::$(echo ${{ github.sha }} | cut -c1-8)"
    - uses: actions/upload-artifact@v3
      with:
        name: jack2-win64-${{ github.event.pull_request.number || steps.slug.outputs.sha8 }}
        path: PawPaw/jack2-win*.exe
    - uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        tag_name: ${{ github.ref_name }}
        name: ${{ github.ref_name }}
        draft: false
        prerelease: false
        files: |
          path: PawPaw/jack2-win*.exe
